### ISSUE TITLE
Charter now links to our security and privacy vulnerability reporting policy

### ISSUE THREAD

**Issue by hober** [privacycg/admin#11]
This is [a minor change](https://github.com/privacycg/privacycg.github.io/pull/13/files) to our [Work Mode](https://privacycg.github.io/charters/2020-03-18.html#work-mode).

This will be discussed on our next call. We'll leave the announcement up until then.

**Comment by npdoty** [comment]
"in this repository"? That suggests reporting security issues related to the `.github` repo inside the privacycg organization, and that repo doesn't have any substantive content. Is this policy intended to capture reporting of all security issues to work proposals developed in repos inside the privacycg organization? Or is the intent for this SECURITY.md file to be copied into each repo, and the privacycg chairs will manage all reports for all work items?

**Comment by npdoty** [comment]
It would be a radical change for every privacy and security issue in a privacy-related spec under development to be reported privately; I don't *think* that's what's intended here, but we should be explicit about it. Feedback and iteration would be much slower, and chairs would become a bottleneck. 

Maybe instead we could give guidance on when it might be useful to provide feedback privately instead of through normal spec development (say, a vulnerability in a widely-shipped feature where you don't believe attackers are already exploiting it).

**Comment by hober** [comment]
> "in this repository"? That suggests reporting security issues related to the `.github` repo inside the privacycg organization, and that repo doesn't have any substantive content.

Repositories called `.github` are special; the policies defined in them apply to all the repositories in the organization. No need to copy these files into the other repos.

**Comment by hober** [comment]
> It would be a radical change for every privacy and security issue in a privacy-related spec under development to be reported privately; I don't _think_ that's what's intended here, but we should be explicit about it. Feedback and iteration would be much slower, and chairs would become a bottleneck.
> 
> Maybe instead we could give guidance on when it might be useful to provide feedback privately instead of through normal spec development (say, a vulnerability in a widely-shipped feature where you don't believe attackers are already exploiting it).

Can you file this [as an issue in that repo](https://github.com/privacycg/.github/issues/new)?
